services:
  - type: web
    name: build-buy-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: "./start.sh"
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONPATH
        value: /opt/render/project/src
